### ISSUE TITLE
Never-ending initialization 

### ISSUE THREAD

**Issue by tslafn** [apexad/homebridge-mysmartblinds-bridge#108]
**Bug or issue information**

The plugin creates one log - "[8/15/2021, 11:14:08 PM] [MySmartBlindsBridge] Initializing MySmartBlindsBridge platform..." and never continues. No further logs shown or blinds added. I have waited over 24 hours. No problems with any other plugins on this homebridge. 

**Homebridge setup information**

Running on Homebridge A1D2 (WIN 8)

homebridge-mysmartblinds-bridge v2.2.9

{
    "name": "MySmartBlindsBridge",
    "username": "------",
    "password": "----",
    "closeUp": true,
    "pollingInterval": 0,
    "allowDebug": true,
    "statusLog": true,
    "platform": "MySmartBlindsBridge"
}

**Comment by apexad** [comment]
Do you have the bridge? https://www.mysmartblinds.com/products/smart-hub

**Comment by tslafn** [comment]
Yep. I’m running v1.21 on the bridge with a good wifi signal strength.

**Comment by tslafn** [comment]
Issue has been resolved. MySmartBlinds platform was blocking the attempt to login. After checking the email (Sent each time the bridge started), and 'unblocking' the IP address (Running on an IOS platform apparently), it works. Didn't even have to restart the bridge.

**Comment by apexad** [comment]
Can you please provide the email with any private details removed?
