### ISSUE TITLE
Reduce log noise

### ISSUE THREAD

**Issue by canadaohcanada** [apexad/homebridge-mysmartblinds-bridge#12]
https://github.com/apexad/homebridge-mysmartblinds-bridge/blob/d8f7f50de3551756f4d8327cbf7eba7a5ea6e091/index.js#L237

https://github.com/apexad/homebridge-mysmartblinds-bridge/blob/d8f7f50de3551756f4d8327cbf7eba7a5ea6e091/index.js#L253

Would it be possible to hide these lines behind a debug config switch? For normal use these lines are noisy. Thanks for this great plugin, I've really enjoyed using it over the past month or so.

**Comment by apexad** [comment]
Definitely! Will get tot his tonight.

**Comment by apexad** [comment]
I always forget to update config schema, so v1.5.1 made the change and v1.5.2 adds to config schema.

**Comment by canadaohcanada** [comment]
Brilliant! Thank you so much.
