### ISSUE TITLE
Cache blind accessories

### ISSUE THREAD

**Issue by nigetech** [apexad/homebridge-mysmartblinds-bridge#13]
I have an issue where every time an update is made available and installed the blinds detected by the plugin are reset and therefore reset in Homekit going back into the default room with default names. This unfortunately causes me an issue in the fact that all setup automations in Homekit are lost and have to be setup again from scratch. Is there anyway of holding the Blind Names in a config file so this isn't lost on each update?

Thanks in advance.

**Comment by apexad** [comment]
I believe homebridge does have some way to cache accessories better than I am doing, I will try and look into this soon.

**Comment by nigetech** [comment]
Perfect thanks, a homebridge Texecom plugin I also use requires each accessory to be specified with any settings in the config file, not sure if that is any help.

**Comment by apexad** [comment]
Just to be clear, one of the primary goals of this plugin was and is ‘no individual creation of blinds in the config’. So, that isn’t an avenue I will pursue.

However, I do believe that there are ways in homebridge to get it to recognize that an accessory created by a the plugin if it restarts is the same one as before (caching basically). I will look into this and update this thread when I am able to verify this to be true or not.

**Comment by nigetech** [comment]
Sounds good, understandable if there is a way of doing it without the use of config amends. It does seem to sporadically lose the accessories or reset them at the moment.

**Comment by apexad** [comment]
Just some context for this issue.
From https://github.com/homebridge/homebridge-examples/blob/master/README.md

> * [Static Platform Plugin](./static-platform-example-typescript): Static platforms know which accessories they want to 
> expose on start up. The set of accessories cannot change over the lifespan of the plugin.
> * [Dynamic Platform Plugin](./dynamic-platform-example-typescript): Dynamic platforms can dynamically add or remove 
> accessories at runtime. Accessories are fully stored to disk by homebridge, and the exact state is reconstructed on
> a reboot. The plugin can store additional context as well. 

Right now this plugin is written as a **Static Platform Plugin** and actually should be a **Dynamic Platform Plugin**.  Will be able to reuse all the code for discovering and controlling blinds, but will be re-writing it from the ground up.  This will be v2.0.0 since it will now cache accessories and I assume reverting to v1.x (which does not cache accessories) will cause issues due to this change.

No ETA, but I'm hoping to do this over the long weekend.

**Comment by nigetech** [comment]
Thanks, I've got the plugin switched off at the minute as it's resetting accessories on a random basis and because of the number of blinds it resets all the names/flows/scenes. Let me know if you need anything tested. Thanks

**Comment by apexad** [comment]
I’ve started working in moving this to a dynamic platform. Hopefully I will get some time this weekend to wrap it up.

**Comment by nigetech** [comment]
Is 1.5.4 fixing this issue or will it still be 2.0.0?
Thanks in advance

**Comment by apexad** [comment]
2.0.0 still. Cleaning up some other things, sorry.

**Comment by nigetech** [comment]
No worries, will keep a watch out for 2.0.0 thanks!

**Comment by apexad** [comment]
Still planning on getting to this soon.  Sorry for the delay.

**Comment by nigetech** [comment]
No worries at all, thanks for the update!

**Comment by apexad** [comment]
Again, I apologize for how long this has taken.  Other things in life as well as some work on other plugins has taken priority.

I finally got the motivation and some time to work on this over the weekend.  Just about wrapped up with it, expect it as v2.0 within the next week or so.

**Comment by nigetech** [comment]
Great, thanks again.

**Comment by apexad** [comment]
2.0.0 released
