### ISSUE TITLE
One of my blinds shows open in Home app even when closed

### ISSUE THREAD

**Issue by ydogandjiev** [apexad/homebridge-mysmartblinds-bridge#134]
**Bug or issue information**
I have six MySmartBlinds installed in my home and this plugin lets me control them via Siri and the Home app which is awesome! Love it! Unfortunately, one of the six blinds seems to always report as open even when it's actually closed by the regularly scheduled on-blinds automation. The issue does not impact the other five blinds.

Here is what it looks like when the issue manifests:
![image](https://user-images.githubusercontent.com/3357245/139795998-f77ed25e-0843-4d18-b780-f75dc09d209c.jpeg)

The blind appears closed but its status shows as open:
![image](https://user-images.githubusercontent.com/3357245/139796118-6cab0c49-f646-4615-a605-59b882057415.png)

I tried removing and re-adding the problematic blind to MySmartBlinds as well as re-calibrating it several times but neither of these actions had any effect on the issue.

**Homebridge setup information**
I'm running Homebridge on a Raspberry Pi that I setup myself. Node version is currently at v14.15.0.

**Logs**
In the HomeLog app I see the blinds reporting their position correctly:
![image](https://user-images.githubusercontent.com/3357245/139795870-052bdf0a-6cdc-451e-8288-77b6f016186e.jpeg)

I can add logs from Homebridge tomorrow since the blinds closing events are no longer visible.

**Comment by apexad** [comment]
This is likely related to #38
