### ISSUE TITLE
Unable to perform initial setup

### ISSUE THREAD

**Issue by bvelazquez1** [apexad/homebridge-mysmartblinds-bridge#140]
I recently received my Smartblinds bridge and completed the setup properly. When installing this plugin, my username and password credentials are correct but nothing happens. I restarted my homebridge and the logs just say "[20/12/2021, 16:44:48] [MySmartBlindsBridge] Initializing MySmartBlindsBridge platform..." Is there a proper setup guide for this plugin? In an attempt to troubleshoot the bridge, I was able to get the blinds working with my Amazon Alexa so I am sure that the bridge is installed properly. But installing this plugin doesn't seem to do anything. I don't see where I can have homebridge auto populate my rollershades.

**Comment by bvelazquez1** [comment]
My node js version is 16.13.0 and my homebridge version is 1.3.8

**Comment by bvelazquez1** [comment]
Additionally, I have 4 rollershades that I control using the "tilt smarthome" app.

**Comment by davilaa** [comment]
I have the same issue. I think the url endpoint is different for shades registered & controlled by Tilt versus “MySmartBlinds”. The weird thing is that the same login works for both. But I cannot register the hub or the roller shades in the “MySmartBlinds” app.

**Comment by apexad** [comment]
Roller shades are different than blinds.
See https://github.com/apexad/homebridge-mysmartrollershades-bridge
 The plugin is incomplete (but all the research into the api is done), but I hope to work on it next year.
