### ISSUE TITLE
Stopped Working When I Switched from HOOBS4 to HomeBridge

### ISSUE THREAD

**Issue by wwkimball** [apexad/homebridge-mysmartblinds-bridge#149]
**Bug or issue information**
> Include as much detail as possible including what is happening and what is expected.

There are so many variables at play here that I'll try to represent everything and work with you to reduce variables until we find the root cause and solution.  I am a software engineer myself, so I'm happy to dig deep with you to trace this out.

As an end-user, here's what I'm experiencing:  The Home app is unable to control any of my blinds and fails to show their status.  When I tap to open a blind or tell Siri via any HomePod Mini to open a blind, the operation simply times-out.  Here's the rub:  this was mostly working two days ago before I made some changes.

When everything was (mostly) working, I was using a HOOBS4 (in a box) with your plugin but I only had 5 blinds converted.  I was excited to try everything out before I finished converting all of my blinds, and was elated that indeed, it was all working "out of the box" with your plugin on the HOOBS4.  Life was good, so I finished converting the rest of my blinds.  I now have 14 automated blinds.  I updated the firmware on each of them as I added them to the vendor's MySmartBlinds app and calibrated them.

When I woke up the next day, most of my automation was failing.  A quick check revealed to me that the HOOBS4 had locked up, hard.  I power-cycled it and noticed immediately that it was suddenly super sluggish.  Adding the blinds with your plugin on a new bridge -- plus everything else I already had on it -- was just too much for that little unit to handle.  So, I made a quick decision to abandon HOOBS.  I have an extremely powerful media server, so I installed HomeBridge via Docker to it and fully recreated all of my configurations from scratch, including your plugin.  I did not use a backup.  This forced me to remove all of the old HOOBS-controlled bridges from my Home and re-add EVERYTHING back into my Home from the new HomeBridge server.  I have a lot of accessories, so this took the greater part of 2 hours.  It was arduous.

However, everything is working again _except the blinds_.  I have checked and double-checked the config for your plugin; there's so little that I can't blame the config.  I even logged into the running HomeBridge's Terminal and ran the `npx homebridge-mysmartblinds-bridge` test; it works.  I get a JSON response showing all of my rooms and blinds with credentials and MACs.  My credentials are solid.  Despite that, I have lost all control over my blinds through the Home app.

I have power-cycled the MySmartBlinds Bridge a few times to no avail.  I don't understand all of its colorful animations but in every case, it seems to eventually settle down into a kind of stand-by mode with the ring fully blue but fading slowly to off and back on to solid blue.  Every once in a while, it'll wake up and put on a dance of blue rotations and then return to what I think is the standby state.

Every time your plugin polls the blinds for their status, this error appears in the HomeBridge log, once for every blind in my Home:

`[MySmartBlindsBridge] STATUS: Family Room Left updateCurrentPosition : 0 (Actual -1)`

That `-1` concerns me.  I could be wrong, but it looks to me like your code is failing to actually communicate with the blinds through the MySmartBlinds Bridge.

Another variable for the mix, if it matters:
After converting the rest of my blinds, when I was still running on the HOOBS, I noticed right away that some blinds furthest away from the MySmartBlinds Bridge were less responsive than others nearer to it.  The MySmartBlinds Bridge claims to work at 200m, but based on my own observations, I sincerely doubt that.  To solve this unrelated issue, I intend to get a second Bridge in the near future to eliminate this range issue.

**Homebridge setup information**
> Include if you are running homebridge directly, using HOOBS, etc...  

I have tried both.  Your plugin was actually working better on the HOOBS4 than it does on a powerful HomeBridge server, other than the HOOBS4 locking up.

> Include details about your configuration if needed, but do not include any email address or password.  

There's nothing special about the configuration.  It's defaults plus my credentials, which are valid.

> Include node version, if known.

```
/homebridge # node --version
v16.14.0
```

**Logs**
> Include logs here.  Be sure to remove any user identifiable information.

On every poll, I'll get 14 pairs of these (I'll only share one pair here because they are all identical except for the name of the room and blind):

```
[2/21/2022, 9:49:43 AM] [MySmartBlindsBridge] Refresh blind Dining Room Main
[2/21/2022, 9:50:09 AM] [MySmartBlindsBridge] STATUS: Dining Room Main updateCurrentPosition : 0 (Actual -1)
```

When I attempt to control a blind via the Home app, I see this (despite the logs indicating a success, the blind never actually moves and the Home app reports "No Response" from the blind I attempted to control):

```
[2/21/2022, 9:54:07 AM] [MySmartBlindsBridge] Dining Room Main setTargetPosition to 100
[2/21/2022, 9:54:33 AM] [MySmartBlindsBridge] STATUS: Dining Room Main updateCurrentPosition : 100 (Actual 100)
[2/21/2022, 9:54:33 AM] [MySmartBlindsBridge] Dining Room Main currentPosition is now 100
```

The very next poll of the same blind shows exactly the same `-1` status as shown above.  The blind never opens.

I should add that the blinds are working via the vendor's MySmartBlinds app, within the limitations of Bluetooth, so there's nothing mechanically wrong with any of the blinds.  I am forced to walk from one end of my house to the other for my phone's BT radio to connect and allow me to individually recognize and control all blinds.  It seems the app doesn't utilize the MySmartBlinds Bridge.

**Comment by apexad** [comment]
Sorry I did not see this sooner.  So first thing I want to note is that there is known issue with this plugin when there a lot of blinds.  However, it does not seem like that is necessarily the issue here.

Indeed, you are correct, the -1 indicates the connection is failing.  In my experience the app should connect via Wifi/Internet so confirm that the bridge is connected to Wifi as expected.

Have you tried removing my plugin, restarted home bridge, confirmed the blinds disappear, and then re-add the plugin?
