### ISSUE TITLE
Hasn't worked for me since app updated to 2.3.9

### ISSUE THREAD

**Issue by dapperdan75** [apexad/homebridge-mysmartblinds-bridge#197]
**Bug or issue information**
> Include as much detail as possible including what is happening and what is expected.

Since the installation of iOS app version 2.3.9 my HomeKit has not been able to control my smartblinds.

**Homebridge setup information**
> Include if you are running homebridge directly, using HOOBS, etc...  
> Include details about your configuration if needed, but do not include any email address or password.  
> Include node version, if known.

I'm running HOOBS 4.3.0 Node version 16.19.1

**Logs**
> Include logs here.  Be sure to remove any user identifiable information.
06/03/2023, 13:38:18Mysmartblinds Bridge BridgeLoaded plugin 'homebridge-mysmartblinds-bridge'
06/03/2023, 13:38:18Mysmartblinds Bridge BridgeLoading 1 platforms...
06/03/2023, 13:38:18Mysmartblinds Bridge BridgeMySmartBlindsBridgeLoading blind from cache: Kitchen Main Window
06/03/2023, 13:38:18Mysmartblinds Bridge BridgeMySmartBlindsBridgeLoading blind from cache: Living Room Main Window
06/03/2023, 13:38:18Mysmartblinds Bridge BridgeMySmartBlindsBridgeLoading blind from cache: Bedroom Main Window
06/03/2023, 13:38:18Mysmartblinds Bridge BridgeMySmartBlindsBridgeLoading blind from cache: Living Room Side Window
06/03/2023, 13:38:18Mysmartblinds Bridge BridgeBridge is running on port 51846.
06/03/2023, 13:38:19Mysmartblinds Bridge BridgeWARNINGunhandled rejection: StatusCodeError: 400 - {"error":"invalid_request","error_description":"OIDC conformant clients cannot use /oauth/ro"}

**Comment by name99-org** [comment]
Just FYI @dapperdan75 this is not a problem with HomeBridge or, exactly, with this plugin, or any updates. The root problem appears to be that the MySmartBlinds server updated/modified the way software authenticates with it, and this plugin has not yet been updated to support the new authentication method.

MySmartBlinds rolled out this change in an extraordinarily kack-handed fashion (at the same time changing a bunch of other things, breaking multiple random functionality, and with zero corporate communication)! However at this point *everything else* seems to be resolved; the only missing piece is the authentication code in the plugin.

If you look at the various issues associated with this plugin, you'll see one with many more responses than all the others. That's probably the best place to track how things are going.

**Comment by dapperdan75** [comment]
> Just FYI @dapperdan75 this is not a problem with HomeBridge or, exactly, with this plugin, or any updates. The root problem appears to be that the MySmartBlinds server updated/modified the way software authenticates with it, and this plugin has not yet been updated to support the new authentication method.
> 
> MySmartBlinds rolled out this change in an extraordinarily kack-handed fashion (at the same time changing a bunch of other things, breaking multiple random functionality, and with zero corporate communication)! However at this point _everything else_ seems to be resolved; the only missing piece is the authentication code in the plugin.
> 
> If you look at the various issues associated with this plugin, you'll see one with many more responses than all the others. That's probably the best place to track how things are going.

Hi - thank you for taking the time to reply.  I have been in touch with MySmartBlinds as my bridge stopped working some time ago.  All you have stated fits with what I've gleaned.

I will look for what you have suggested to see if I can ascertain whether we are anywhere near a solution.

I am quite new to all this so forgive any unintended breaches of etiquette!

**Comment by Swop1925** [comment]
@dapperdan75 did you at least get your bridge working (without home bridge)?  I FINALLY got mine back to "normal". Let me know if you need help.  As for Homebridge plugin, we have to wait for an update to resolve the authentication issues.  As @name99-org mentioned, MySmartBlinds did all of this in about the worst possible way one can imagine - it's been an absolute shitshow and while I'm stuck with the blinds and bridge now, I certainly won't be buying any new products form them again.  Anyway, if your bridge is still busted and customer service can't help (they were useless for me... literally just stopped replying to my requests for help), just let me know and I'll try to guide you through steps.

**Comment by randymassey** [comment]
Of interest, I have not that I recall seeing any updates from Alex, or the plug-in author… Has there been any feedback from Alex about his timetable?  If he’s even working on the plug-in??But agreed, the bridge & app spills be working now as per its normal use.RandySent from my iPhoneOn Apr 2, 2023, at 12:57 PM, Swop1925 ***@***.***> wrote:﻿
@dapperdan75 did you at least get your bridge working (without home bridge)?  I FINALLY got mine back to "normal". Let me know if you need help.  As for Homebridge plugin, we have to wait for an update to resolve the authentication issues.  As @name99-org mentioned, MySmartBlinds did all of this in about the worst possible way one can imagine - it's been an absolute shitshow and while I'm stuck with the blinds and bridge now, I certainly won't be buying any new products form them again.  Anyway, if your bridge is still busted and customer service can't help (they were useless for me... literally just stopped replying to my requests for help), just let me know and I'll try to guide you through steps.

**Comment by dapperdan75** [comment]
HiThanks for your offer. My bridge is now working again (except via Himebridge).RegardsSent from my iPhoneOn 2 Apr 2023, at 20:57, Swop1925 ***@***.***> wrote:﻿
@dapperdan75 did you at least get your bridge working (without home bridge)?  I FINALLY got mine back to "normal". Let me know if you need help.  As for Homebridge plugin, we have to wait for an update to resolve the authentication issues.  As @name99-org mentioned, MySmartBlinds did all of this in about the worst possible way one can imagine - it's been an absolute shitshow and while I'm stuck with the blinds and bridge now, I certainly won't be buying any new products form them again.  Anyway, if your bridge is still busted and customer service can't help (they were useless for me... literally just stopped replying to my requests for help), just let me know and I'll try to guide you through steps.
