### ISSUE TITLE
Plug-in is not auto detecting my blinds

### ISSUE THREAD

**Issue by ColeDimich** [apexad/homebridge-mysmartblinds-bridge#206]
**Bug or issue information**
The connection with the blinds has been very spotty and unresponsive since setup about 6 months ago. I cleared the blinds from the cached accessories, uninstalled the plugin and removed the bridge from HomeKit. I went through the entire setup process again including deleting the bridge from the MySmartBlinds app and repairing it several times but cannot get Homebridge to recognize and auto detect the blinds again. The bridge seems to work fine and allows me to add it to HomeKit, it just doesn’t display any of the connected blinds in either Homebridge or HomeKit 

**Homebridge setup information**
Running homebridge locally installed on an iMac fully updated to v1.6.1 with node 18.16.0

**Comment by apexad** [comment]
The authentication system changed and the plugin will be need to be updated.  Don't have an ETA yet
