### ISSUE TITLE
Rollershade support

### ISSUE THREAD

**Issue by bvelazquez1** [apexad/homebridge-mysmartblinds-bridge#212]
Do you have any plans to add support for the Tilt Rollershades? It's part of the same company and uses the same Bridge.

**Comment by apexad** [comment]
I did at one point, see https://github.com/apexad/homebridge-mysmartrollershades-bridge for how far I got.  They are same bridge and same company but there were enough differences to where it made sense to me to make it a different project. Over on that repo there are issues with some reverse engineering of the roller shades and it would probably be pretty easy for someone to get it working, but I don't currently have the time.

**Comment by apexad** [comment]
re-opening so that a future dev sees this

**Comment by jamesstineheath** [comment]
There is now a tested local implementation for Tilt RollerShades: https://github.com/Sunrise-Labs-Dot-AI/tilt-local-bridge

It runs on a Raspberry Pi and talks directly to the shades over encrypted BLE, with exact positions, battery, and availability via Home Assistant MQTT discovery. Tilt's legacy service is used during pairing to issue a new per-shade BLE key; runtime control is local. It is not a native Homebridge plugin, but Home Assistant can expose the covers to HomeKit, and the protocol implementation may help add direct RollerShade support here.
