### ISSUE TITLE
Way to hide blinds

### ISSUE THREAD

**Issue by name99-org** [apexad/homebridge-mysmartblinds-bridge#23]
I understand that you want to make the plugin as simple as possible for most people, and I applaud that and the auto discovery/auto-population. However I would like a way to suppress the presentation of a blind.

The reason is that, god knows why, but my MySmartBlinds account seems to be have screwed itself up somewhere on either the server or in the hub, so that 
- the APP (correctly) only thinks I have two blinds BUT 
- your plugin (so the server end?) thinks I have three blinds, one an old blind that no longer exists.

Since I cannot see the bad blind in the app, I cannot delete it there.
I can do some control on the HomeKit side -- name it "bad" and stick it in a room I don't care about. But there is one remaining problem, namely that this non-existent blind is believed by the server (or some part of the system) to have 0% battery. And that pollutes apps like Eve (and perhaps one day Home.app, when it gets its act together) to constantly display a warning that I have a 0% battery device. In an ideal world I'd like to get rid of this!

As far as I can tell there is no way, within HomeKit, to delete a device that is presented by a hub -- all I can do is get the hub to stop presenting it. Hence the request. 

Presumably the easiest/least disruptive way to do this is something like have an optional array in the config (never created by most users) listing a collection of Room/BlindName strings?

**Comment by apexad** [comment]
Have you upgraded to 2.0.4 and tried deleting the blind from the cache in Homebridge UI?  Otherwise can you turn on debug mode and get me some logs?

**Comment by name99-org** [comment]
Hi,

Sorry for the delay. As you may know, there was some excitement in the US this weekend!

OK, to answer your questions:
(a) I am running 2.0.4 
(b) I don't believe this is a caching issue in the sense you're suggesting, not a cache on your side. My fake/non-existent blind existed before I installed the MySmartBlinds plugin. (It was created about a month ago, and I was waiting until my last blind was installed, about three days ago, before activating the Homebridge plugin).

I'm not sure quite what I do to get logs. I switched on logging via the GUI, and restarted. 
What's printed in the console during startup is (starting just above what looks relevant)

11/9/2020, 6:41:36 PM] [vFullDark] Setting switch to true
[11/9/2020, 6:41:36 PM] [MySmartBlindsBridge] Loading blind from cache: TV Room TV West
[11/9/2020, 6:41:36 PM] [MySmartBlindsBridge] Loading blind from cache: Stairs South
[11/9/2020, 6:41:36 PM] [MySmartBlindsBridge] Loading blind from cache: Stairs South
[11/9/2020, 6:41:36 PM] [MySmartBlindsBridge] Loading blind from cache: Bedroom West
Setup Payload:
X-HM://0024AOLL3NI9A
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 499-70-503 │     
    └────────────┘     
                       
[11/9/2020, 6:41:36 PM] Homebridge is running on port 51877.
HAP Warning: Characteristic undefined not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
Validation of `id_token` requires a `clientSecret` when using the HS256 algorithm. To ensure tokens are validated, please switch the signing algorithm to RS256 or provide a `clientSecret` in the constructor.
[11/9/2020, 6:41:43 PM] [MySmartBlindsBridge] auth0Token refresh, now expires 2020-11-10T12:41:42.000Z



Note how Stairs South is duplicated. 
TV Room TV West,
Bedroom West,
and ONE OF the Stairs South 
are legit. The second Stairs South is not.

The duplicate names is not an issue, worst case I can call the valid one Stairs StairsSouth, or whatever and it will then differ from the invalid one. 
The issue is the fact that the second (fake) blind exists in your view of the world because you're being fed incorrect information by the MySmartBlinds server. 

Thanks,
Maynard

**Comment by apexad** [comment]
Can you turn on Allow Debug logs in the plugin settings?

**Comment by apexad** [comment]
Just fo confirm this is not a cache issue, if you are using homebridge, try going here: http://homebridge.local/settings
Click the icon by 'Remove Single Cached Accessory' and remove all the homebridge-mysmartblinds-bridge cached objects and restart.

**Comment by name99-org** [comment]
I have logs switched on, but I don't know where I should find them to send to you.
> 


I went to the settings page (never knew that was there!), deleted the incorrect blind and restarted. 
Things looked good for about a minute --- the deleted blind disappeared from Home.app
But then it came back... I assume your side did some interaction with the server, learned that there was a discrepancy (the server has the one extra blind that you don't know about) so the server updated you, you updated the cache, and we're back to the original problem :-(

**Comment by apexad** [comment]
Remove all the blinds from there, not jus the incorrect one.

**Comment by name99-org** [comment]
No joy :-(

Removed all four blinds, restarted HomeKit. 

After a minute Home.app displays:
Note we now have the (renamed, to prevent confusion) Stairs StairsSouth (good) blind along with the fake Stairs South blind. 
All (not surprisingly) transplanted back to the same room as where the HomeBridge Hub has been placed. 






On Nov 9, 2020, at 7:37 PM, Alex Martin <notifications@github.com> wrote:


Remove all the blinds from there, not jus the incorrect one.

**Comment by apexad** [comment]
Logs should show something like this: https://github.com/apexad/homebridge-mysmartblinds-bridge/issues/22#issuecomment-721689836_

**Comment by name99-org** [comment]
OK, splitting into two messages bcs your relay rejected the two images.

> Begin forwarded message:
> 
> From: Maynard Handley <name99@name99.org>
> Subject: Re: [apexad/homebridge-mysmartblinds-bridge] Way to hide blinds (#23)
> Date: November 9, 2020 at 8:24:46 PM PST
> To: apexad/homebridge-mysmartblinds-bridge <reply@reply.github.com>
> 
> OK, I found /Users/handleym/.homebridge/homebridge.log
> It has MySmartBlinds Logging on, and Homebridge -D. I'm not sure if there's any additional logging/debugging flag I should switch on.
> 
> The only interesting stuff seems to be what I've grepped out. If it's necessary I can send you the whole thing.
> 
> What I see is much less data than your link. 
> 
> 
>

**Comment by name99-org** [comment]
part 2 of 2

> 
> Just to be safe I also turned on MySmartBlinds status change logging. Now we get:
> 
> 
> 
>

**Comment by apexad** [comment]
You’ll have to copy the text and paste. If you are trying to send screenshots it does not seem to be working.

**Comment by name99-org** [comment]
Hi Alex,

Sorry about that! I sent you screenshots because they have nice coloring, which makes it easier to see the important stuff ASAP, rather than just a wall of text.

But the good news is that, as far as I am concerned, the problem is solved :-)
Purely by accident I discovered that in the MySmartBlinds app, if you tap the space ABOVE where all the rooms are listed, you get a list of all blinds, independent of their rooms. And this list included by fake nonexistent blind which had become detached from any room! So I could delete it, it's gone from the server, gone from your list, gone from HomeKit. And everything is working exactly as it should. Very sweet!

Thanks for being so willing to help with this. I've sent you a little donation via PayPal in gratitude :-)

**Comment by apexad** [comment]
Great to hear that you figured it out. I may add a note about this to the README for future users.  Thanks for the PayPal donation too!
