### ISSUE TITLE
Blinds Not Responding

### ISSUE THREAD

**Issue by forresthamilton** [apexad/homebridge-mysmartblinds-bridge#49]
**Bug or issue information**
The blinds do not respond to commands via HomeKit but respond from the native MySmartBlinds app. Homebridge shows the command being sent to the blinds but no movement occurs from the blinds. It worked for the first day or so. Rebooting homebridge does not fix issue.

**Homebridge setup information**
> homebridge directly
>  "name": "MySmartBlindsBridge",
            "username": "email@gmail.com",
            "password": "password",
            "closeUp": true,
            "pollingInterval": 0,
            "allowDebug": true,
            "statusLog": true,
            "platform": "MySmartBlindsBridge"
> node version v14.15.4

**Logs**
[1/31/2021, 9:33:35 AM] [MySmartBlindsBridge] Living Room Right Window setTargetPosition to 0
[1/31/2021, 9:34:01 AM] [MySmartBlindsBridge] Living Room Right Window currentPosition is now 0

**Comment by apexad** [comment]
Any errors when you turn on the logs?
Also, is the issue with all blinds or just a single blind?

**Comment by forresthamilton** [comment]
No errors in the logs. All blinds.

**Comment by arcticgenes** [comment]
mine just started doing the same thing

**Comment by arcticgenes** [comment]
I’m happy to report that after a power cycle of the smart blinds bridge, things are working again.  I decided to give it a try after I noticed the blinds were working in the app if I was on cellular with Bluetooth turned off.

**Comment by apexad** [comment]
Seems like this maybe an issue with the bridge itself, not this plugin if it can be resolved via restart of the device.  Either way without logs from the original poster showing some kind of error, there is not much I can do.
