### ISSUE TITLE
Log Error

### ISSUE THREAD

**Issue by chuckktn** [apexad/homebridge-mysmartblinds-bridge#66]
**Bug or issue information**
> Include as much detail as possible including what is happening and what is expected.

**Homebridge setup information**
> Include if you are running homebridge directly, using HOOBS, etc...  
> Include details about your configuration if needed, but do not include any email address or password.  
> Include node version, if known.

[homebridge-mysmartblinds-bridge] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 199 exceeded maximum of 100

I am getting these errors constantly.  Not sure what to do about it.

**Logs**
> Include logs here.  Be sure to remove any user identifiable information.

**Comment by apexad** [comment]
Fascinating, thought I was account for this with some fancy math, but it appears not.  Homebridge is 0 to 100 and MySmarBlinds is actually 0 to 200 so it's fun to make those work together.  Do you use the 'close up' feature of this plugin? or not?

**Comment by chuckktn** [comment]
No I didn’t use the close up

**Comment by apexad** [comment]
Try turning the 'Close up' config option on and see if this gets rid of the warnings.

**Comment by apexad** [comment]
Scratch that, I will deploy a fix for this in a moment.

**Comment by chuckktn** [comment]
OK.. I am new to this.. how do I get it when you deploy it?

Where you from?  Nashville TN area here

**Comment by apexad** [comment]
Assuming you are using Homebridge Config UI X it will prompt you in bit that there is an update for your plugin.  In this case mysmartblinds and it will be from 2.2.6 to 2.2.7

I'm in Phoenix, AZ

**Comment by chuckktn** [comment]
Cool man I appreciate it..   I have had troubles with these blinds since I installed them.. just getting most of the bugs out of them..   thanks for the help

**Comment by chuckktn** [comment]
I updated it tonight..  I am getting this message now.

[4/6/2021, 7:57:05 PM] [homebridge-mysmartblinds-bridge] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://git.io/JtMGR for more info.

**Comment by randymassey** [comment]
I’ve been seeing this too, both under the previous HOOBS set up, as well as now under the new home bridge set up. 

But that’s also the only complaint reference I’m seeing now under HomeBridge in the logs.  (Runs son much better).

RM

**Comment by apexad** [comment]
should be fixed in 2.2.9 (battery level warning).  Seems like MySmartBlinds rarely actually gives a good reading for battery level.  Potentially could get rid of it.

**Comment by chuckktn** [comment]
You are right.. mine show battery almost dead.. but they are not..

**Comment by apexad** [comment]
yeah, I may just get rid of battery level completely then in a future update

**Comment by chuckktn** [comment]
It is working now.. Great.. thanks bro

**Comment by randymassey** [comment]
Alex I would ask if you could leave it in for the battery, unless it causes you problems from a code standpoint. 

I know sometimes they can get out of sync if they have not updated & show 0%, But I  actually do use that with the homepods and I find them at least in my set up to be pretty accurate, (obviously not when showing zero).

I did have two of the blind units with batteries that were not charging and holding a charge correctly, those were replaced by my smart blinds & no issue since. 

But I tend to find the batt percentage in HomeKit matches pretty accurately the status bar that shows in their app at least to the degree that the status bar represents a full 0-100 percentage scale.

Just my 2 cents.

Randy
